"""
GymOps report generator.

Generates the weekly CI Workout Digest as a Markdown file.
This file is published as a GitHub Actions artifact named 'ci-workout-digest'.
"""

from datetime import date, timedelta
from pathlib import Path

from gymops.db import get_all_prs, get_workouts_in_range


def generate_digest(days: int = 7, output_dir: Path = Path(".")) -> str:
    """
    Generate a Markdown digest of recent workout activity.

    Scans the last N days of workout history, counts total sets logged,
    lists new/updated PRs during the period, and writes a Markdown file.

    Args:
        days: Number of days to include in the digest window.
        output_dir: Directory where the digest file will be written.

    Returns:
        The filename of the generated digest (e.g., 'digest_2026-06-22.md').
    """
    today = date.today()
    since = today - timedelta(days=days)
    filename = f"digest_{today.isoformat()}.md"
    output_path = output_dir / filename

    workouts = get_workouts_in_range(days=days)
    all_prs = get_all_prs()

    # Group workouts by exercise
    by_exercise: dict[str, list] = {}
    for w in workouts:
        by_exercise.setdefault(w.exercise_name, []).append(w)

    # Build the Markdown content
    lines: list[str] = [
        f"# GymOps CI Workout Digest",
        f"",
        f"**Period:** {since.isoformat()} → {today.isoformat()} ({days} days)  ",
        f"**Total Sets Logged:** {len(workouts)}  ",
        f"**Exercises Trained:** {len(by_exercise)}  ",
        f"",
        f"---",
        f"",
        f"## 📊 Workout Summary",
        f"",
        f"| Exercise | Sets Logged | Best Weight (kg) | Best Est. 1RM (kg) |",
        f"|:---------|------------:|-----------------:|-------------------:|",
    ]

    for ex_name, logs in sorted(by_exercise.items()):
        best_weight = max(w.weight for w in logs)
        best_1rm = max(w.epley_1rm for w in logs)
        lines.append(
            f"| {ex_name} | {len(logs)} | {best_weight:.1f} | {best_1rm:.1f} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"## 🏆 Personal Records",
        f"",
    ]

    if all_prs:
        lines += [
            f"| Exercise | Max Weight (kg) | Est. 1RM (kg) | Date |",
            f"|:---------|----------------:|--------------:|-----:|",
        ]
        for pr in all_prs:
            lines.append(
                f"| {pr.exercise_name} | {pr.max_weight:.1f} | "
                f"{pr.max_epley_1rm:.1f} | {str(pr.timestamp)[:10]} |"
            )
    else:
        lines.append("_No personal records set yet._")

    lines += [
        f"",
        f"---",
        f"",
        f"_Generated by GymOps on {today.isoformat()}_",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return filename
